backend:
  name: github
  repo: chanchaltsynapse/decap-site
  branch: main

  # IMPORTANT: must match your OAuth server
  base_url: http://52.167.43.197
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

site_url: http://52.167.43.197
display_url: http://52.167.43.197

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Body"
        name: "body"
        widget: "markdown"
